#!/bin/sh 
# Utility to  auto-run xmly.py; creates OpenRadar procedures file and FGFS Sid/Star Rm routes according to given ICAO name 
MNAM=${0##*/} && MNAM=${MNAM%%.*}
NAM1=${1##*/} && NAM1=${NAM1%%.*}
UNAM="PATHwhoami" 
DNAM=${MNAM}
if [ "$1" = "-h " ]  
then 
echo "$MNAM Utility to  auto-run xmly.py; creates OpenRadar procedures file and FGFS Sid/Star Rm routes according to given ICAO name "
fi 
###  Edit / Change these pathNames for your system  
# subfolder with arg1 icaoName ( e.g. OpenRadar/data/routes )will be written with ORDR procedures and spec 
ORDRPATH="/comm/fpln/test"
#ORDRPATH="/apkg/apFgfs/OpenRadar/data/routes"
# subfolder with arg1 icaoName ( e.g. ~/.fgfs/Export ) will be written with FGFS Route Manager V2 Sid, Star, Transition Routes
FGEXPATH="/comm/fpln/genrRMV2"
#FGEXPATH="/home/otto/.fgfs/Export"
###
#echo mkdir -p "$ORDRPATH/$NAM1"
mkdir -p "$ORDRPATH/$NAM1"
#echo "mkdir -p $FGEXPATH/$NAM1"
mkdir -p "$FGEXPATH/$NAM1"
cd       "$FGEXPATH/$NAM1"
#
echo "xmly.py -f ARDR -i /data/ARDP/STARDP.txt -n $NAM1 -g ORDR -o $ORDRPATH/$NAM1/aXmly-$NAM1.procedures.xml -k $ORDRPATH/$NAM1/aXmly.$NAM1.skel.txt"
read -n1 -r -p  "$MNAM Rdy  OK  ( AnyKey or Ctl-C to exit)"
#
xmly.py -f ARDP -i /data/ARDP/STARDP.txt -n $NAM1 -g ORDR -o $ORDRPATH/$NAM1/aXmly-$NAM1.procedures.xml -k $ORDRPATH/$NAM1/aXmly-$NAM1.skel.txt 
#cp    $ORDRPATH/$NAM1/aXmly-$NAM1.skel.txt $ORDRPATH/$NAM1/aXmly-$NAM1.spec.txt
nedit $ORDRPATH/$NAM1/aXmly-$NAM1.skel.txt $ORDRPATH/$NAM1/aXmly-$NAM1.spec.txt
#
read   -n1 -r -p "PATH xmly.py -f ARDP -i /data/ARDP/STARDP.txt -n $NAM1 -g RMV2 -o $ORDRPATH/$NAM1/aXmly-$NAM1.procedures.xml -s $ORDRPATH/$NAM1/aXmly-$NAM1.spec.txt OK ?? AnyKey or Ctl-C to exit"
xmly.py -f ARDP -i /data/ARDP/STARDP.txt -n $NAM1 -g RMV2 -o $ORDRPATH/$NAM1/aXmly-$NAM1.rmv2.xml -s $ORDRPATH/$NAM1/aXmly-$NAM1.spec.txt
read   -n1 -r -p "PATH xmly.py -f ARDP -i /data/ARDP/STARDP.txt -n $NAM1 -g ORDR -o $ORDRPATH/$NAM1/aXmly-$NAM1.procedures.xml -s $ORDRPATH/$NAM1/aXmly-$NAM1.spec.txt OK ?? AnyKey or Ctl-C to exit"
xmly.py -f ARDP -i /data/ARDP/STARDP.txt -n $NAM1 -g ORDR -o $ORDRPATH/$NAM1/aXmly-$NAM1.procedures.xml -s $ORDRPATH/$NAM1/aXmly-$NAM1.spec.txt
echo "  "
